Bootstrapの導入
yanbaru-expert/team_project_58 pull request #26
Opened 2021-09-11 02:10 UTC by suugakusan

close #8 

## 実装内容
- Bootstrap を導入
  - Bootstrap は 4.5.1 をインストール
  - CSS を Sprockets で扱うように設定

## 確認内容
実際に、home/indexページを作り、bootstrapが適用されていることを確認しました

## 参考資料
- 【やんばるエキスパート教材】Bootstrap
  - [やんばるエキスパートアプリ](https://www.yanbaru-code.com/texts/216)

## チェックリスト
- [ ] GitHub で Files changed を確認
- [ ] 影響し得る範囲のローカル環境での動作確認
- [ ] `rubocop -a` を実行

2021-09-11 15:02 UTC, great084 requested changes
`issues.md`が書き換わっています。
不要なファイル（修正すべきではないもの、意図せぬもの）を修正していないか確認した上で、プルリクを出すようにしましょう。

2021-09-11 15:02 UTC, great084 commented on config/environments/development.rb
> +  config.hosts.clear
この設定はなんのためでしょうか？
cloud9使ってます？？

2021-09-11 21:15 UTC, suugakusan commented on config/environments/development.rb
> +  config.hosts.clear
cloud9を使っていました。

2021-09-12 09:02 UTC, great084 approved these changes
LGTMです！

2021-09-12 09:33 UTC, merged